In [54]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
print("loaded libs")

loaded libs


In [55]:
cancer = datasets.load_breast_cancer()

In [56]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [57]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [58]:
cancer.data[0:3]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [77]:
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.1,random_state=109) 
# 70% training and 30% test

In [78]:
print("data",cancer.data.shape)
print("target", cancer.target.shape)
print("X train",X_train.shape)
print("y train", y_train.shape)
print("X test", X_test.shape)
print("y test", y_test.shape)

data (569, 30)
target (569,)
X train (512, 30)
y train (512,)
X test (57, 30)
y test (57,)


In [79]:
clf = svm.SVC(kernel='linear')
clf.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [80]:
y_pred = clf.predict(X_test)

In [81]:
y_pred.shape

(57,)

In [82]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))
#https://en.wikipedia.org/wiki/Precision_and_recall

Accuracy: 0.9649122807017544
Precision: 0.9714285714285714
Recall: 0.9714285714285714


In [83]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1])

In [85]:
X_test[0]

array([1.167e+01, 2.002e+01, 7.521e+01, 4.162e+02, 1.016e-01, 9.453e-02,
       4.200e-02, 2.157e-02, 1.859e-01, 6.461e-02, 2.067e-01, 8.745e-01,
       1.393e+00, 1.534e+01, 5.251e-03, 1.727e-02, 1.840e-02, 5.298e-03,
       1.449e-02, 2.671e-03, 1.335e+01, 2.881e+01, 8.700e+01, 5.506e+02,
       1.550e-01, 2.964e-01, 2.758e-01, 8.120e-02, 3.206e-01, 8.950e-02])

In [86]:
y_pred[0]

1